"""add home_station, office_station, home_office_confirmed to users

Revision ID: 16ea4b7ba3e8
Revises: 17423ce290e0
Create Date: 2026-07-31 14:13:20.603835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16ea4b7ba3e8'
down_revision: Union[str, None] = '17423ce290e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_station', sa.String(), nullable=True))
    op.add_column('users', sa.Column('office_station', sa.String(), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'home_office_confirmed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'home_office_confirmed')
    op.drop_column('users', 'office_station')
    op.drop_column('users', 'home_station')
    # ### end Alembic commands ###
