"""add trip route_or_direction and user home/office route_or_direction

Revision ID: eae11c8bfa68
Revises: f8b0d08644c5
Create Date: 2026-08-03 00:30:36.299357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eae11c8bfa68'
down_revision: Union[str, None] = 'f8b0d08644c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('route_or_direction', sa.String(), nullable=True))
    op.add_column('users', sa.Column('home_route_or_direction', sa.String(), nullable=True))
    op.add_column('users', sa.Column('office_route_or_direction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'office_route_or_direction')
    op.drop_column('users', 'home_route_or_direction')
    op.drop_column('trips', 'route_or_direction')
    # ### end Alembic commands ###
