"""add home_mode office_mode fcm_token to users

Revision ID: f8b0d08644c5
Revises: 16ea4b7ba3e8
Create Date: 2026-08-02 21:21:13.760752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8b0d08644c5'
down_revision: Union[str, None] = '16ea4b7ba3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('home_mode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('office_mode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.drop_column('users', 'office_mode')
    op.drop_column('users', 'home_mode')
    # ### end Alembic commands ###
